version: '4.12'
services:
  track_time-db:
    image: postgres:15
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: track_time
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      MAX_CONNECTIONS: 300
    restart: always
    ports:
      - "5555:5432"
    command: [
        "postgres",
        "-c", "shared_preload_libraries=pg_stat_statements",
    ]